spring.application.name: spring-boot-graphql
server.port: 8080

# LOGGING
logging.level.com.spring.boot: DEBUG
logging.pattern.console: ${CONSOLE_LOG_PATTERN:-%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %4line %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}}

# Enable GraphQL Servlet
graphql:
  # GraphQL Java Tools
  tools:
    schema-location-pattern: "**/*.graphqls"
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: true
    cors:
      allowed-origins: http://some.domain.com
    # if you want to @ExceptionHandler annotation for custom GraphQLErrors
    exception-handlers-enabled: true
    contextSetting: PER_REQUEST_WITH_INSTRUMENTATION
    # Tracing and Metrics
    tracing-enabled: true
    actuator-metrics: true

altair:
  enabled: true
  mapping: /altair
  endpoint.graphql: /graphql
  pageTitle: Altair
  props.resources.variables: graphqls/altair/variables.graphql
