server:
  port: 8082

logging:
  level:
    com.spring.boot: debug

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.242.129:3306/quartz2?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: PassW0rd321
  quartz:
    job-store-type: "jdbc"
    jdbc:
      initialize-schema: "always" # 每次启动应用都会初始化数据库
      schema: classpath:schema/tables_mysql.sql # 初始化脚本
    startup-delay: 30s # 应用启动后等30秒定时任务再启动
    properties: # 配置quartz属性
      # Configure ThreadPool
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      org.quartz.threadPool.threadCount: 25 # 最多25个job同时运行，默认10个
      org.quartz.threadPool.threadPriority: 5
      # Configure JobStore
      org.quartz.jobStore.misfireThreshold: 60000
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 20000

