spring.shardingsphere.datasource.names: write-ds-0,write-ds-1,write-ds-0-read-0,write-ds-0-read-1,write-ds-1-read-0,write-ds-1-read-1

spring.shardingsphere.datasource.write-ds-0.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.write-ds-0.driver-class-name: com.p6spy.engine.spy.P6SpyDriver
spring.shardingsphere.datasource.write-ds-0.jdbc-url: jdbc:p6spy:mysql://192.168.136.135:3306/write-ds-0?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.shardingsphere.datasource.write-ds-0.username: root
spring.shardingsphere.datasource.write-ds-0.password: PassW0rd321

spring.shardingsphere.datasource.write-ds-0-read-0.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.write-ds-0-read-0.driver-class-name: com.p6spy.engine.spy.P6SpyDriver
spring.shardingsphere.datasource.write-ds-0-read-0.jdbc-url: jdbc:p6spy:mysql://192.168.136.135:3306/write-ds-0-read-0?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.shardingsphere.datasource.write-ds-0-read-0.username: root
spring.shardingsphere.datasource.write-ds-0-read-0.password: PassW0rd321

spring.shardingsphere.datasource.write-ds-0-read-1.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.write-ds-0-read-1.driver-class-name: com.p6spy.engine.spy.P6SpyDriver
spring.shardingsphere.datasource.write-ds-0-read-1.jdbc-url: jdbc:p6spy:mysql://192.168.136.135:3306/write-ds-0-read-1?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.shardingsphere.datasource.write-ds-0-read-1.username: root
spring.shardingsphere.datasource.write-ds-0-read-1.password: PassW0rd321

spring.shardingsphere.datasource.write-ds-1.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.write-ds-1.driver-class-name: com.p6spy.engine.spy.P6SpyDriver
spring.shardingsphere.datasource.write-ds-1.jdbc-url: jdbc:p6spy:mysql://192.168.136.135:3306/write-ds-1?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.shardingsphere.datasource.write-ds-1.username: root
spring.shardingsphere.datasource.write-ds-1.password: PassW0rd321

spring.shardingsphere.datasource.write-ds-1-read-0.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.write-ds-1-read-0.driver-class-name: com.p6spy.engine.spy.P6SpyDriver
spring.shardingsphere.datasource.write-ds-1-read-0.jdbc-url: jdbc:p6spy:mysql://192.168.136.135:3306/write-ds-1-read-0?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.shardingsphere.datasource.write-ds-1-read-0.username: root
spring.shardingsphere.datasource.write-ds-1-read-0.password: PassW0rd321

spring.shardingsphere.datasource.write-ds-1-read-1.type: com.zaxxer.hikari.HikariDataSource
spring.shardingsphere.datasource.write-ds-1-read-1.driver-class-name: com.p6spy.engine.spy.P6SpyDriver
spring.shardingsphere.datasource.write-ds-1-read-1.jdbc-url: jdbc:p6spy:mysql://192.168.136.135:3306/write-ds-1-read-1?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
spring.shardingsphere.datasource.write-ds-1-read-1.username: root
spring.shardingsphere.datasource.write-ds-1-read-1.password: PassW0rd321

# default-database-strategy
spring.shardingsphere.rules.sharding.default-database-strategy.standard.sharding-column: user_id
spring.shardingsphere.rules.sharding.default-database-strategy.standard.sharding-algorithm-name: database-inline

# binding-tables
spring.shardingsphere.rules.sharding.binding-tables[0]: t_order,t_order_item

# broadcast-tables
spring.shardingsphere.rules.sharding.broadcast-tables: t_address

# sharding
# t_order
# 表达式 `ds_$->{0..1}`枚举的数据源为读写分离配置的逻辑数据源名称
spring.shardingsphere.rules.sharding.tables.t_order.actual-data-nodes: ds-$->{0..1}.t_order_$->{0..1}
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-column: order_id
spring.shardingsphere.rules.sharding.tables.t_order.table-strategy.standard.sharding-algorithm-name: t-order-inline

spring.shardingsphere.rules.sharding.tables.t_order.key-generate-strategy.column: order_id
spring.shardingsphere.rules.sharding.tables.t_order.key-generate-strategy.key-generator-name: snowflake

# t_order_item
spring.shardingsphere.rules.sharding.tables.t_order_item.actual-data-nodes: ds-$->{0..1}.t_order_item_$->{0..1}
spring.shardingsphere.rules.sharding.tables.t_order_item.table-strategy.standard.sharding-column: order_id
spring.shardingsphere.rules.sharding.tables.t_order_item.table-strategy.standard.sharding-algorithm-name: t-order-item-inline

spring.shardingsphere.rules.sharding.tables.t_order_item.key-generate-strategy.column: order_item_id
spring.shardingsphere.rules.sharding.tables.t_order_item.key-generate-strategy.key-generator-name: snowflake

# 分布式序列算法配置
spring.shardingsphere.rules.sharding.key-generators.snowflake.type: SNOWFLAKE

# 分片算法配置
# database
spring.shardingsphere.rules.sharding.sharding-algorithms.database-inline.type: INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.database-inline.props.algorithm-expression: ds-$->{user_id % 2}

# t-order
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-inline.type: INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-inline.props.algorithm-expression: t_order_$->{order_id % 2}

# t-order-item
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-item-inline.type: INLINE
spring.shardingsphere.rules.sharding.sharding-algorithms.t-order-item-inline.props.algorithm-expression: t_order_item_$->{order_id % 2}

# 读写分离策略配置
# ds_0,ds_1 为读写分离配置的逻辑数据源名称
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds-0.type: Static
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds-0.props.write-data-source-name: write-ds-0
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds-0.props.read-data-source-names: write-ds-0-read-0, write-ds-0-read-1

spring.shardingsphere.rules.readwrite-splitting.data-sources.ds-1.type: Static
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds-1.props.write-data-source-name: write-ds-1
spring.shardingsphere.rules.readwrite-splitting.data-sources.ds-1.props.read-data-source-names: write-ds-1-read-0, write-ds-1-read-1

# 负载均衡算法配置
spring.shardingsphere.rules.readwrite-splitting.load-balancers.read-random.type: RANDOM

# sharding-jdbc打印SQL
spring.shardingsphere.props.sql-show: true
