spring:
  data:
    mongodb:
      host: 192.168.242.129
      port: 27017
#      additional-hosts:
#        - "mongoserver2.example.com:23456"
      database: test
      username: root
      password: PassW0rd321
