spring:
  application:
    name: spring-boot-data-mongodb
  data:
    mongodb:
      uri: mongodb://localhost:27017/test?retryWrites=true&w=majority
#      additional-hosts:
#        - "mongoserver2.example.com:23456"
      username: root
      password: PassW0rd321

logging:
  level:
    com.spring.boot: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
