spring:
  application:
    name: spring-boot-arthas

server:
  port: 8091

arthas:
  agent-id: hsehdfsfghhwertyfad
  tunnel-server: ws://47.75.156.201:7777/ws

management:
  endpoints:
    web:
      exposure:
        include: "arthas"

